### ISSUE TITLE
Postaviti prvu verziju projekta

### ISSUE THREAD

**Issue by vdavid033** [amujkic/iooa2020-projekt#1]

**Comment by amujkic** [comment]
[Projekt.zip](https://github.com/amujkic/iooa2020-projekt/files/4678451/Projekt.zip)

**Comment by amujkic** [comment]
Nadopuna prvog dijela i korekcija oko dijela Log in-a, Sign-upa i konekcije sa MongoDB-om
[Projekt.zip](https://github.com/amujkic/iooa2020-projekt/files/4686586/Projekt.zip)

**Comment by amujkic** [comment]
Finalna stranica uz par nedostataka
[Projekt_IOOA.zip](https://github.com/amujkic/iooa2020-projekt/files/4770225/Projekt_IOOA.zip)
